# Generated by Django 6.0.2 on 2026-03-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='Inventory_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
