# Generated by Django 6.0.2 on 2026-03-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
